# Generated by Django 4.2.2 on 2023-08-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
